modmap:  
  - name: Global  
    remap:  
      CapsLock: Esc  
      F13: F12  
  
virtual_modifiers:  
  - KEY_GRAVE  
  
keymap:  
  - name: KEY_GRAVE combinations  
    remap:  
      KEY_GRAVE-q: Shift-8           # (  
      KEY_GRAVE-w: Shift-9           # )  
      KEY_GRAVE-e: Shift-7           # /  

      KEY_GRAVE-a: KEY_RIGHTALT-8    # [
      KEY_GRAVE-s: KEY_RIGHTALT-9    # ]
      KEY_GRAVE-d: KEY_RIGHTALT-KEY_MINUS    # \
      KEY_GRAVE-z: KEY_RIGHTALT-7    # {
      KEY_GRAVE-x: KEY_RIGHTALT-0    # }

      KEY_GRAVE-1: Shift-2           # '
      KEY_GRAVE-2: KEY_GRAVE         # itself (paradox)
      KEY_GRAVE-3: KEY_RIGHTALT-KEY_BACKSLASH # `

      KEY_INSERT: KEY_DELETE # Unbroken Delete Key

      F14: KEY_RIGHTALT-KEY_RIGHTBRACE # tilde
